# Sets default memory used for gradle commands. Can be overridden by user or command line properties.
org.gradle.jvmargs=-Xmx1G
org.gradle.daemon=true
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.configuration-cache=true
org.gradle.vfs.watch=false

parchment_minecraft_version=1.21.1
parchment_mappings_version=2024.11.17
# Environment Properties
minecraft_version=1.21.1
# The Minecraft version range can use any release version of Minecraft as bounds.
# Snapshots, pre-releases, and release candidates are not guaranteed to sort properly
# as they do not follow standard versioning conventions.
minecraft_version_range=[1.21.1]
# The Neo version must agree with the Minecraft version to get a valid artifact
neo_version=21.1.244
loader_version_range=[1,)

## Mod Properties
mod_id=cnmb
mod_name=Create Needs More Bullets
mod_license=MIT
mod_version=0.0.1
mod_group_id=net.pod.cnmb

#dependencies
# Create
create_version = 6.0.10-280
ponder_version = 1.0.82
flywheel_version = 1.0.6
registrate_version = MC1.21-1.3.0+67

#JEI
mc_version=1.21
jei_version=19.5.0.59

geckolib_version=4.9.2
